### ISSUE TITLE
config.toml doesn't render if "features" is commented out of default.toml

### ISSUE THREAD

**Issue by gsloan-chef** [Indellient/bldr_package_sync#8]
the default.toml that ships here has this line:
`# features=["PACKAGE_VERSIONS"]`

With that line commented out like that, the config file fails to render:

`Failed to compile configuration: Error rendering "config.toml" line 5, col 12: Can't serialize parameter to TOML: unsupported Rust type`

Changing it to the following resolves it: 
`features=[]`

**Comment by skylerto** [comment]
Thanks for opening this issue!

Seems like this is the interpreted toml from the habitat config, I'm going to be putting together a fix as we speak.
